/**
 * AI Sports Desk Page
 * 
 * Live intelligence feed powered by SportBot Agent.
 * Real-time sports news, analysis, and insights.
 */

import { Metadata } from 'next';
import AISportsDesk from '@/components/AISportsDesk';
import { META, SITE_CONFIG, getAIDeskSchema } from '@/lib/seo';

export const metadata: Metadata = {
  title: META.aiDesk.title,
  description: META.aiDesk.description,
  keywords: META.aiDesk.keywords,
  openGraph: {
    title: META.aiDesk.title,
    description: META.aiDesk.description,
    url: `${SITE_CONFIG.url}/ai-desk`,
    siteName: SITE_CONFIG.name,
    type: 'website',
    images: [
      {
        url: `${SITE_CONFIG.url}/og-ai-desk.png`,
        width: 1200,
        height: 630,
        alt: 'AI Sports Desk - Real-Time Intelligence Feed',
      },
    ],
  },
  twitter: {
    card: 'summary_large_image',
    title: META.aiDesk.title,
    description: META.aiDesk.description,
    site: SITE_CONFIG.twitter,
  },
  alternates: {
    canonical: `${SITE_CONFIG.url}/ai-desk`,
  },
};

export default function AIDeskPage() {
  const jsonLd = getAIDeskSchema();
  
  return (
    <>
      {/* JSON-LD Structured Data */}
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }}
      />
      
      <main className="min-h-screen bg-bg">
        <div className="max-w-4xl mx-auto px-4 py-8">
        {/* Page Header */}
        <div className="mb-8">
          <div className="flex items-center gap-3 mb-2">
            <div className="w-12 h-12 bg-gradient-to-br from-primary/30 to-accent/30 rounded-xl flex items-center justify-center border border-white/10">
              <span className="text-2xl">🧠</span>
            </div>
            <div>
              <h1 className="text-2xl font-bold text-white">AI Sports Desk</h1>
              <p className="text-text-muted text-sm">Live Intelligence Feed</p>
            </div>
          </div>
          <p className="text-text-secondary mt-4 max-w-2xl">
            Real-time sports intelligence powered by SportBot Agent. Get instant updates on injuries, 
            lineups, market movements, and AI-driven match insights — all in one place.
          </p>
        </div>

        {/* Feature Badges */}
        <div className="flex flex-wrap gap-2 mb-8">
          <span className="px-3 py-1.5 bg-purple-500/10 text-purple-400 text-xs font-medium rounded-full border border-purple-500/20 flex items-center gap-1.5">
            <span>⚡</span> Real-Time Data
          </span>
          <span className="px-3 py-1.5 bg-blue-500/10 text-blue-400 text-xs font-medium rounded-full border border-blue-500/20 flex items-center gap-1.5">
            <span>📋</span> Lineup Intel
          </span>
          <span className="px-3 py-1.5 bg-green-500/10 text-green-400 text-xs font-medium rounded-full border border-green-500/20 flex items-center gap-1.5">
            <span>📊</span> Market Moves
          </span>
          <span className="px-3 py-1.5 bg-orange-500/10 text-orange-400 text-xs font-medium rounded-full border border-orange-500/20 flex items-center gap-1.5">
            <span>🏥</span> Injury Updates
          </span>
        </div>

        {/* Main Feed */}
        <div className="bg-bg-secondary border border-white/10 rounded-2xl p-6">
          <AISportsDesk limit={15} />
        </div>

        {/* Info Card */}
        <div className="mt-8 bg-white/5 border border-white/10 rounded-xl p-5">
          <h3 className="text-sm font-semibold text-white mb-2 flex items-center gap-2">
            <span>ℹ️</span> About AI Sports Desk
          </h3>
          <p className="text-text-muted text-sm leading-relaxed">
            SportBot Agent monitors live sports news and provides instant analysis. 
            Posts are generated by AI using real-time web data and should be used for 
            informational purposes only. This is not betting advice.
          </p>
        </div>
      </div>
    </main>
    </>
  );
}
